# Generated by Django 3.0.7 on 2020-06-27 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=256, verbose_name='Vezetéknév')),
                ('first_name', models.CharField(max_length=256, verbose_name='Keresztnév')),
                ('id_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Igazolvány szám')),
                ('pmpsz_number', models.CharField(blank=True, max_length=8, null=True, unique=True, verbose_name='PMPSZ azonosító')),
            ],
        ),
        migrations.CreateModel(
            name='Duty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duty_type', models.CharField(choices=[('O', 'Önálló'), ('R', 'Rendőrrel közös'), ('Re', 'Rendezvénybiztosítás'), ('K', 'Kutyás'), ('E', 'Egyéb')], default='O', max_length=2, verbose_name='Szolgálat típusa')),
                ('date', models.DateField(verbose_name='Dátum')),
                ('hours', models.PositiveSmallIntegerField(default=0, verbose_name='Szolgálati órák')),
                ('commander', models.BooleanField(default=False, verbose_name='Járőrparancsnok')),
                ('kms', models.PositiveSmallIntegerField(default=0, verbose_name='Megtett kilométerek')),
                ('plate', models.CharField(blank=True, max_length=6, null=True, verbose_name='Rendszám')),
                ('help', models.PositiveSmallIntegerField(default=0, verbose_name='Segítségnyújtás (fő)')),
                ('retention', models.BooleanField(default=False, verbose_name='Visszatartás')),
                ('caught', models.BooleanField(default=False, verbose_name='Tettenérés')),
                ('missing', models.BooleanField(default=False, verbose_name='Eltűnt személy felkutatása')),
                ('signal', models.BooleanField(default=False, verbose_name='Jelzésadás')),
                ('other', models.BooleanField(default=False, verbose_name='Egyéb eset')),
                ('member', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='time_sheet.Member', verbose_name='Szolgálatot ellátó személy')),
            ],
            options={
                'unique_together': {('member', 'date', 'duty_type')},
            },
        ),
    ]
