# Generated by Django 3.0.7 on 2020-06-27 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_sheet', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='member',
            unique_together={('first_name', 'last_name')},
        ),
    ]
