# Generated by Django 3.0.7 on 2020-06-28 09:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('time_sheet', '0003_auto_20200628_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='reg_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
