# Generated by Django 3.0.7 on 2020-06-29 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_sheet', '0004_member_reg_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Aktív tag'),
        ),
        migrations.AddField(
            model_name='member',
            name='dog',
            field=models.BooleanField(default=False, verbose_name='Kutyás polgárőr'),
        ),
        migrations.AddField(
            model_name='member',
            name='motor',
            field=models.BooleanField(default=False, verbose_name='Motoros polgárőr'),
        ),
        migrations.AddField(
            model_name='member',
            name='young',
            field=models.BooleanField(default=False, verbose_name='Ifjú polgárőr'),
        ),
    ]
