# Generated by Django 3.0.7 on 2020-07-01 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('time_sheet', '0005_auto_20200629_1553'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='duty',
            options={'ordering': ['member']},
        ),
        migrations.AlterField(
            model_name='duty',
            name='member',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.SET_DEFAULT, to='time_sheet.Member', verbose_name='Szolgálatot ellátó személy'),
        ),
    ]
