# Generated by Django 3.0.7 on 2020-07-01 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_sheet', '0006_auto_20200701_1438'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='duty',
            options={},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['last_name']},
        ),
    ]
