# Generated by Django 3.0.7 on 2020-07-03 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_sheet', '0007_auto_20200701_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='owner',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Tulajdonos'),
        ),
    ]
