# Generated by Django 3.0.7 on 2020-07-03 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_sheet', '0008_car_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Szín'),
        ),
        migrations.AddField(
            model_name='car',
            name='stripped',
            field=models.BooleanField(default=False, verbose_name='Felszerelt járőrautó'),
        ),
    ]
