# Generated by Django 3.0.7 on 2020-07-13 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_sheet', '0009_auto_20200703_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duty',
            name='duty_type',
            field=models.CharField(choices=[('O', 'Önálló'), ('R', 'Rendőrrel közös'), ('Re', 'Rendezvénybiztosítás'), ('K', 'Kutyás'), ('Er', 'Egyéb rendvédelmi szervvel'), ('E', 'Egyéb')], default='O', max_length=2, verbose_name='Szolgálat típusa'),
        ),
    ]
